server:
  port: 9192

spring:
  datasource:
    username: shax
    password: shax
    url: jdbc:mysql://localhost:3306/your_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true